In [5]:
import pickle
import numpy as np
import collections

In [9]:
%time data = pickle.load(open("../data/parsed/WIKI_100K_train.dump", "rb"))

CPU times: user 373 ms, sys: 1.54 s, total: 1.91 s
Wall time: 2.64 s


In [10]:
%time data.sum()

CPU times: user 777 ms, sys: 1.68 s, total: 2.46 s
Wall time: 2.67 s


139097861

In [ ]:
%time km = data.dot(data.T)

---

In [68]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

In [38]:
X, y = make_classification(n_samples=10000)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

---

In [74]:
%%time

km = linear_kernel(X_train)

clf = SVC(kernel="precomputed", random_state=0)
clf.fit(km, y_train)

CPU times: user 944 ms, sys: 277 ms, total: 1.22 s
Wall time: 1.44 s


In [75]:
clf.n_support_

array([340, 339], dtype=int32)

In [76]:
tkm = linear_kernel(X_test, X_train)
y_pred = clf.predict(tkm)
confusion_matrix(y_test, y_pred)

array([[958,  24],
       [ 29, 989]])

---

In [77]:
%%time

km = linear_kernel(X_train)
km[km > 0] = 0

clf = SVC(kernel="precomputed", random_state=0)
clf.fit(km, y_train)

CPU times: user 1.08 s, sys: 224 ms, total: 1.3 s
Wall time: 1.24 s


In [78]:
clf.n_support_

array([801, 801], dtype=int32)

In [79]:
tkm = linear_kernel(X_test, X_train)
tkm[tkm > 0] = 0
y_pred = clf.predict(tkm)
confusion_matrix(y_test, y_pred)

array([[785, 197],
       [184, 834]])

---